exchange: okx
symbol: BTC/USDT
timeframe: 1h
since_days: 365
fetch_limit_per_call: 1000

bollinger_window: 20
bollinger_std: 2.0
rsi_window: 14
macd_fast: 12
macd_slow: 26
macd_signal: 9

onchain_csvs: []

horizon: 1

lstm:
  lookback: 64
  epochs: 25
  batch_size: 64
  units: 64
  dropout: 0.2
  learning_rate: 0.001
  patience: 5

walkforward:
  n_splits: 5
  test_size_ratio: 0.15
  val_ratio: 0.2

backtest:
  long_threshold: 0.002
  short_threshold: -0.002
  fee_rate: 0.0005

seed: 1337
